# Generated by Django 4.2.7 on 2024-01-10 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precipitation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('very_good', 'Very good'), ('good', 'Good'), ('moderate', 'Moderate'), ('sufficient', 'Sufficient'), ('poor', 'Poor'), ('very_poor', 'Very poor')], default='poor', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weather', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='air_quality', to='weatherandair.weather')),
            ],
        ),
    ]
