# Generated by Django 4.2.7 on 2024-01-02 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='date_recorded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
