# Generated by Django 4.2.7 on 2024-01-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weather_date_recorded'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('quality', models.CharField(choices=[('bardzo_dobry', 'Bardzo dobry'), ('dobry', 'Dobry'), ('umiarkowany', 'Umiarkowany'), ('dostateczny', 'Dostateczny'), ('zly', 'Zły'), ('bardzo_zly', 'Bardzo zły'), ('brak_indeksu', 'Brak indeksu')], default='zly', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
