# Generated by Django 4.2.7 on 2024-01-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_airquality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airquality',
            name='quality',
            field=models.CharField(choices=[('bardzo_dobra', 'Bardzo dobra'), ('dobra', 'Dobry'), ('umiarkowana', 'Umiarkowana'), ('dostateczna', 'Dostateczna'), ('zla', 'Zła'), ('bardzo_zla', 'Bardzo zła')], default='zly', max_length=20),
        ),
    ]
