# Generated by Django 4.2.7 on 2024-01-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_rename_date_recorded_weather_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airquality',
            name='quality',
            field=models.CharField(choices=[('very_good', 'Very good'), ('good', 'Good'), ('moderate', 'Moderate'), ('sufficient', 'Sufficient'), ('poor', 'Poor'), ('very_poor', 'Very poor')], default='poor', max_length=20),
        ),
    ]
